#pragma once
#include "cinder/CinderResources.h"

#define ASSETS_PATH "Assets"
#define IMAGE_PATH "Images"
#define JSON_PATH "Json"
#define DEFAULT_PATH "Default"
#define WORKING_PATH "Working"

#define SHADERS_PATH "Shaders"
#define SETTINGS_PATH "Settings"
#define PRESETS_PATH "Presets"

#define WINDOW_PATH "window.json"
#define CAMERA_PATH "cam.json"

#define APP_UI "transform"
#define BACKGROUND_UI "background"
#define POST_UI "post prcess"
#define AUDIO_UI "audio input"
#define OSC_UI "osc"
#define EXPORTER_UI "exporter"
#define PHYSICS_UI "physics"
#define PARTICLE_UI "particles"
#define CAMERA_UI "camera"
#define POINTS_UI "points"
#define SPRITES_UI "sprites"
#define PLEXUS_UI "plexus"
#define LINES_UI "lines"
#define TRAIL_UI "trail"
#define PRIMITIVE_UI "primitive"
#define PRIMITIVE_GEOMETRY_UI "primitive geometry"
#define RIBBON_UI "ribbon"
#define TRAIL_POINTS_UI "trail points"
